// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiitlafljkibbwzdcatr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaXRsYWZsamtpYmJ3emRjYXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDE2MzksImV4cCI6MjA2MTI3NzYzOX0.twLVoOef7x8icvyokkglQl8kHydd7f9wT_Cf29q5EkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);